package com.example.test.mapper;

import com.example.test.pojo.Spmtest;
import com.example.test.pojo.SpmtestExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpmtestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    long countByExample(SpmtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int deleteByExample(SpmtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int insert(Spmtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int insertSelective(Spmtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    List<Spmtest> selectByExample(SpmtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    Spmtest selectByPrimaryKey(Integer id);

    List<Spmtest> queryAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Spmtest record, @Param("example") SpmtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int updateByExample(@Param("record") Spmtest record, @Param("example") SpmtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int updateByPrimaryKeySelective(Spmtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spmtest
     *
     * @mbg.generated Fri Sep 27 17:49:39 CST 2019
     */
    int updateByPrimaryKey(Spmtest record);
}